# Generated by Django 6.0.3 on 2026-04-25 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_otp_user_otp_expires_user_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bus_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='license_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
