# Generated by Django 6.0.3 on 2026-04-24 04:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0002_stop_alter_bus_driver_remove_route_stops_routestop_and_more'),
        ('tracking', '0003_buslocation_speed_passengerwaiting_from_stop_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaleTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tracking.trip')),
            ],
        ),
        migrations.CreateModel(
            name='UserRoutePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pref_from', to='buses.stop')),
                ('to_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pref_to', to='buses.stop')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='route_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
