# Generated by Django 6.0.3 on 2026-05-13 12:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0003_alter_bus_driver'),
        ('tracking', '0005_emergencyalert_passengercountlog_stoparrival'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['driver', 'status'], name='tracking_tr_driver__42dc83_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['status', 'start_time'], name='tracking_tr_status_b8117d_idx'),
        ),
    ]
