# Generated by Django 6.0.3 on 2026-07-08 03:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0006_trip_tracking_tr_driver__42dc83_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RideRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(max_length=20)),
                ('pickup_lat', models.FloatField()),
                ('pickup_lng', models.FloatField()),
                ('pickup_address', models.CharField(blank=True, max_length=200)),
                ('dest_lat', models.FloatField()),
                ('dest_lng', models.FloatField()),
                ('dest_address', models.CharField(blank=True, max_length=200)),
                ('distance_km', models.FloatField(default=0)),
                ('estimated_fare', models.FloatField(default=0)),
                ('final_fare', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('searching', 'Searching Driver'), ('accepted', 'Driver Accepted'), ('arrived', 'Driver Arrived'), ('started', 'Ride Started'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='searching', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('cash', 'Cash Paid'), ('online', 'Online Paid')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('arrived_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_by', models.CharField(blank=True, max_length=20)),
                ('cancel_reason', models.TextField(blank=True)),
                ('cancellation_fee', models.FloatField(default=0)),
                ('no_show_marked_at', models.DateTimeField(blank=True, null=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ride_assignments', to=settings.AUTH_USER_MODEL)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RideDriverOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offered_at', models.DateTimeField(auto_now_add=True)),
                ('response', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('timeout', 'Timeout')], default='pending', max_length=20)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='tracking.riderequest')),
            ],
        ),
        migrations.CreateModel(
            name='NoShowLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='no_shows', to=settings.AUTH_USER_MODEL)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.riderequest')),
            ],
        ),
        migrations.CreateModel(
            name='UserViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_type', models.CharField(max_length=50)),
                ('detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='riderequest',
            index=models.Index(fields=['passenger', 'status'], name='tracking_ri_passeng_d34692_idx'),
        ),
        migrations.AddIndex(
            model_name='riderequest',
            index=models.Index(fields=['driver', 'status'], name='tracking_ri_driver__65d54e_idx'),
        ),
        migrations.AddIndex(
            model_name='riderequest',
            index=models.Index(fields=['vehicle_type', 'status'], name='tracking_ri_vehicle_a6a9a4_idx'),
        ),
    ]
